-- TEMP

/*

UPDATE Resources
SET TechReveal = NULL;

UPDATE Resources
SET TechCityTrade = 'TECH_FISHING';

*/

-- BUILDS

UPDATE Builds
SET PrereqTech = 'TECH_TRAPPING'
WHERE Type = 'BUILD_CAMP';

UPDATE Builds
SET PrereqTech = 'TECH_BOAT_BUILDING'
WHERE Type = 'BUILD_FISHING_BOATS';

UPDATE Builds
SET PrereqTech = 'TECH_FARMING'
WHERE Type = 'BUILD_FARM';

UPDATE Builds
SET PrereqTech = 'TECH_MASONRY'
WHERE Type = 'BUILD_QUARRY';

UPDATE Builds
SET PrereqTech = 'TECH_WOOD_CUTTING'
WHERE Type = 'BUILD_LUMBERMILL';

UPDATE Builds
SET PrereqTech = 'TECH_WOOD_CUTTING'
WHERE Type = 'BUILD_REMOVE_FOREST';

UPDATE Builds
SET PrereqTech = 'TECH_DOMESTICATION'
WHERE Type = 'BUILD_PASTURE';

UPDATE Builds
SET PrereqTech = 'TECH_CONSTRUCTION'
WHERE Type = 'BUILD_FORT';

UPDATE Builds
SET PrereqTech = 'TECH_MINING'
WHERE Type = 'BUILD_MINE';

UPDATE Builds
SET PrereqTech = 'TECH_TRADE'
WHERE Type = 'BUILD_ROAD';

UPDATE Builds
SET PrereqTech = 'TECH_CALENDAR'
WHERE Type = 'BUILD_PLANTATION';

UPDATE Builds
SET PrereqTech = 'TECH_IRON_WORKING'
WHERE Type = 'BUILD_REMOVE_JUNGLE';

UPDATE Builds
SET PrereqTech = 'TECH_LOCAL_MARKETS'
WHERE Type = 'BUILD_TRADING_POST';

UPDATE Builds
SET PrereqTech = 'TECH_IRRIGATION'
WHERE Type = 'BUILD_REMOVE_MARSH';

UPDATE Builds
SET PrereqTech = 'TECH_MILITARY_SCIENCE'
WHERE Type = 'BUILD_CITADEL';

UPDATE Builds
SET PrereqTech = 'TECH_INDUSTRIALISM'
WHERE Type = 'BUILD_WELL';

UPDATE Builds
SET PrereqTech = 'TECH_INDUSTRIALISM'
WHERE Type = 'BUILD_OFFSHORE_PLATFORM';

-- PROCESSES

UPDATE Processes SET TechPrereq = NULL WHERE Type = 'PROCESS_WEALTH';
UPDATE Processes SET TechPrereq = 'TECH_SCHOLARSHIP' WHERE Type = 'PROCESS_RESEARCH';

-- FEATURES - experimental changes

/*

UPDATE Features
SET ArtDefineTag = 'ART_DEF_FEATURE_CRATER'
WHERE Type = 'FEATURE_OASIS';

UPDATE Features
SET NaturalWonder = 1
WHERE Type = 'FEATURE_OASIS';

*/

-- END